-- Load the CSV with the Python ingestion script so blank TotalCharges values
-- are cleaned consistently and repeat imports safely upsert customer rows.
-- From the repository root, run:
--   python -m scripts.load_data --create-schema
-- Configure DATABASE_URL (see .env.example) before running the command.
